In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,'sudh',4.6+7j])  ## Upcasting

array(['1', '2', '3', '4', '5', 'sudh', '(4.6+7j)'], dtype='<U64')

In [7]:
np.array([1,2,3,4, 7.8])            ## Upcasting

array([1. , 2. , 3. , 4. , 7.8])

In [9]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [12]:
type(np.array([[1,2], [3,4]]))

numpy.ndarray

In [14]:
np.array([[1,2], [3,4], [6,7]])   # 2D Array

array([[1, 2],
       [3, 4],
       [6, 7]])

In [15]:
np.array([[1,2], [3,4], [6,7,8]])

C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_17020/2922002003.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2], [3,4], [6,7,8]])


array([list([1, 2]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [16]:
np.array([[[1,3], [3,4]], [[5,6], [8,9]]])

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

In [17]:
np.array([1,2,3], ndmin = 3)  # 3D Array

array([[[1, 2, 3]]])

In [18]:
np.array([1,2,3], ndmin = 6)  # 6D Array

array([[[[[[1, 2, 3]]]]]])

In [20]:
np.array([1,2,3], ndmin=2, dtype = complex)

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [21]:
np.array([(1,2), (3,4)])

array([[1, 2],
       [3, 4]])

In [63]:
arr = np.array([(1,2), (3,4)], dtype = [('a', '<i2'), ('b', '<i8')])  # Mapping intType

In [64]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [65]:
arr[0]

(1, 2)

In [66]:
arr[0][0]

1

In [67]:
type(arr[0][0])  # a is i2(16bit)

numpy.int16

In [68]:
type(arr[0][1])  # b is i8(64bit)

numpy.int64

In [69]:
type(arr[1][0])  # a is i2(16bit)

numpy.int16

In [70]:
type(arr[1][1])  # b is i8(64bit)

numpy.int64

In [71]:
# i1: 8bit
# i2: 16bit
# i4: 32bit
# i8: 64bit
# mutiple of 8

In [72]:
arr = np.array([(1,2), (3,4)], dtype = [('a', '<i2'), ('b', '<f8')])  # Mapping intType

In [73]:
type(arr[1][1])  # b is f8(64bit)

numpy.float64

In [74]:
arr = np.array([[1,2], [3,4]])

In [75]:
arr

array([[1, 2],
       [3, 4]])

In [76]:
arr[0]

array([1, 2])

In [77]:
arr[0][1]

2

In [79]:
type(arr[0][1])   # Default int is int32

numpy.int32

In [88]:
# Creating matrix
mat = np.mat(arr)

In [89]:
mat

matrix([[1, 2],
        [3, 4]])

In [90]:
type(np.mat(arr))

numpy.matrix

In [91]:
l = [3,4,5,76,7]

In [92]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [93]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [94]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [95]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [96]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [97]:
issubclass(np.matrix, np.ndarray)

True

In [98]:
issubclass(np.ndarray, np.matrix)

False

In [99]:
arr

array([[1, 2],
       [3, 4]])

In [100]:
a = arr         # Soft Copy

In [101]:
a

array([[1, 2],
       [3, 4]])

In [102]:
b = np.copy(arr)  # Deep Copy

In [103]:
b

array([[1, 2],
       [3, 4]])

In [104]:
arr[0][0] = 67

In [105]:
arr

array([[67,  2],
       [ 3,  4]])

In [106]:
a        # a reflecting the changes

array([[67,  2],
       [ 3,  4]])

In [107]:
b        # b not reflecting the changes

array([[1, 2],
       [3, 4]])

In [108]:
id(arr)

2633289875056

In [109]:
id(a)

2633289875056

In [110]:
id(b)

2633291036400

In [112]:
id(arr) == id(a)

True

In [113]:
id(arr) == id(b)

False

In [114]:
arr

array([[67,  2],
       [ 3,  4]])

In [115]:
arr[0: 10]

array([[67,  2],
       [ 3,  4]])

In [116]:
arr[-1]

array([3, 4])

In [117]:
arr[::-1]

array([[ 3,  4],
       [67,  2]])

In [118]:
for i in arr:
    print(i)

[67  2]
[3 4]


In [124]:
np.fromfunction(lambda i, j : i==j, (4,4))  #fromfunction generate ndarry from function

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [125]:
np.fromfunction(lambda i, j : i*j, (3,3))  #fromfunction generate ndarry from function

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [127]:
np.fromfunction(lambda i, j : i+j+10, (3,3))  #fromfunction generate ndarry from function

array([[10., 11., 12.],
       [11., 12., 13.],
       [12., 13., 14.]])

In [128]:
np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function

C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_17020/1442271528.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function
C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_17020/1442271528.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [129]:
# 0/0: nan, 1/0: inf, 2/0: inf

In [130]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [134]:
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x000002651C6E7D60>

In [132]:
def test(x):
    yield x

In [133]:
test(5)

<generator object test at 0x000002651C6E7B30>

In [135]:
gen

<generator object <genexpr> at 0x000002651C6E7D60>

In [136]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [137]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [138]:
gen

<generator object <genexpr> at 0x000002651C6E7D60>

In [141]:
np.fromstring('1,3,4,5', sep=',', dtype=int)

array([1, 3, 4, 5])

In [142]:
np.fromstring('101,375,4412,512', sep=',')

array([ 101.,  375., 4412.,  512.])

In [148]:
arr = np.array(l)
arr

array([ 3,  4,  5, 76,  7])

In [145]:
arr1 = np.array([[1,2,3,4], [5,6,7,8], [3,6,9,3]])

In [146]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 6, 9, 3]])

In [150]:
type(arr)

numpy.ndarray

In [156]:
arr1.size

12

In [151]:
arr1.ndim

2

In [152]:
arr1.shape

(3, 4)

In [153]:
arr1.dtype

dtype('int32')

In [154]:
arr

array([ 3,  4,  5, 76,  7])

In [155]:
arr.size

5

In [157]:
arr.ndim

1

In [158]:
arr.shape

(5,)

In [163]:
arr2 = np.array([[[1,3,5,7], [3,4,23,4]], [[5,6,1,1], [8,9,2,2]]])

In [164]:
arr2.size

16

In [165]:
arr2.ndim

3

In [167]:
arr2.shape  # 2 number of 2x4 dimension

(2, 2, 4)

In [172]:
arr2[0]

array([[ 1,  3,  5,  7],
       [ 3,  4, 23,  4]])

In [168]:
arr2[0][0][0]

1

In [173]:
arr2[1]

array([[5, 6, 1, 1],
       [8, 9, 2, 2]])

In [175]:
arr2[1][0][0]

5

In [176]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [177]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [178]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [179]:
np.arange(6.6, 9, 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [180]:
np.arange(6.6, 9, -0.3)

array([], dtype=float64)

In [182]:
np.arange(9, 6.6, -0.3)    # arange dont exclude the upperbound

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [183]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [184]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [186]:
np.linspace(.3, 1.2, 5)

array([0.3  , 0.525, 0.75 , 0.975, 1.2  ])

In [187]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [188]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [189]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [190]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [191]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [192]:
np.ones((2,3,4))+10

array([[[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]],

       [[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]]])

In [194]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [196]:
np.eye(4)  # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [197]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [198]:
np.linspace(2,4,4, endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [200]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [201]:
np.linspace(2,4,4, endpoint=False, axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [205]:
np.linspace([1,6], 4)

array([[1.        , 6.        ],
       [1.06122449, 5.95918367],
       [1.12244898, 5.91836735],
       [1.18367347, 5.87755102],
       [1.24489796, 5.83673469],
       [1.30612245, 5.79591837],
       [1.36734694, 5.75510204],
       [1.42857143, 5.71428571],
       [1.48979592, 5.67346939],
       [1.55102041, 5.63265306],
       [1.6122449 , 5.59183673],
       [1.67346939, 5.55102041],
       [1.73469388, 5.51020408],
       [1.79591837, 5.46938776],
       [1.85714286, 5.42857143],
       [1.91836735, 5.3877551 ],
       [1.97959184, 5.34693878],
       [2.04081633, 5.30612245],
       [2.10204082, 5.26530612],
       [2.16326531, 5.2244898 ],
       [2.2244898 , 5.18367347],
       [2.28571429, 5.14285714],
       [2.34693878, 5.10204082],
       [2.40816327, 5.06122449],
       [2.46938776, 5.02040816],
       [2.53061224, 4.97959184],
       [2.59183673, 4.93877551],
       [2.65306122, 4.89795918],
       [2.71428571, 4.85714286],
       [2.7755102 , 4.81632653],
       [2.

In [206]:
np.linspace([1,6], 4, endpoint=False, axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [207]:
np.linspace([1,6], 4, endpoint=False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [208]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [209]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [210]:
np.logspace([2],[3])

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [211]:
d = np.linspace(4,7,40)

In [212]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [213]:
d.ndim

1

In [214]:
d.shape

(40,)

In [216]:
# Changing the shape to 2d
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [219]:
d.reshape(2,1,20)   # convert in such way so that elements will remain same

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [221]:
d.reshape(2,2,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [222]:
d.reshape(2,4,5)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231],
        [4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308],
        [5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385],
        [5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462],
        [6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [225]:
np.random.rand(3)   # Gaussian/normal Distribution

array([0.8577679 , 0.46350072, 0.14375556])

In [226]:
np.random.randn(5)  # standard normal distribution(mean=0, sd=1)

array([ 0.03808334, -1.40342807,  1.17972403,  0.85562146, -1.61694176])

In [228]:
np.random.randn(2,2,3)

array([[[ 0.11763431, -0.6887765 ,  0.94547039],
        [ 3.31164914,  0.38489171,  1.18951598]],

       [[ 1.2591865 , -2.50925257, -0.0115705 ],
        [ 0.9243167 ,  0.16916911,  2.19640271]]])

In [229]:
np.random.randint(5,60)

20

In [230]:
np.random.randint(5,60, (4,4))

array([[27, 53, 15, 33],
       [59, 43, 50, 18],
       [37, 48, 34, 16],
       [51, 31, 29, 33]])

In [231]:
arr = np.random.randint(3,9, (3,3))

In [232]:
arr

array([[7, 4, 7],
       [7, 3, 8],
       [6, 3, 6]])

In [233]:
arr.reshape(1,9)

array([[7, 4, 7, 7, 3, 8, 6, 3, 6]])

In [234]:
arr.reshape(9,1)

array([[7],
       [4],
       [7],
       [7],
       [3],
       [8],
       [6],
       [3],
       [6]])

In [235]:
arr.reshape(3,3)

array([[7, 4, 7],
       [7, 3, 8],
       [6, 3, 6]])

In [236]:
arr.reshape(1,1,9)

array([[[7, 4, 7, 7, 3, 8, 6, 3, 6]]])

In [237]:
arr.reshape(3,3,1)

array([[[7],
        [4],
        [7]],

       [[7],
        [3],
        [8]],

       [[6],
        [3],
        [6]]])

In [238]:
arr.reshape(3, -1)

array([[7, 4, 7],
       [7, 3, 8],
       [6, 3, 6]])

In [240]:
arr.reshape(9, -12321312)

array([[7],
       [4],
       [7],
       [7],
       [3],
       [8],
       [6],
       [3],
       [6]])

In [241]:
# (3, -ve)  by giving -ve number it will automatically reshape by using the first number here its 3

In [242]:
arr

array([[7, 4, 7],
       [7, 3, 8],
       [6, 3, 6]])

In [244]:
arr.max()

8

In [245]:
arr = np.random.randint(4,100, (5,5))

In [246]:
arr

array([[76, 59, 64, 69, 33],
       [61, 54, 56, 49, 74],
       [81, 44, 98, 32, 72],
       [29, 15, 99, 92, 47],
       [ 4, 93,  8, 76, 89]])

In [248]:
arr[3:, 3:]

array([[92, 47],
       [76, 89]])

In [249]:
arr[:, [1,3]]

array([[59, 69],
       [54, 49],
       [44, 32],
       [15, 92],
       [93, 76]])

In [250]:
arr[[0,1,3], :]

array([[76, 59, 64, 69, 33],
       [61, 54, 56, 49, 74],
       [29, 15, 99, 92, 47]])

In [251]:
arr

array([[76, 59, 64, 69, 33],
       [61, 54, 56, 49, 74],
       [81, 44, 98, 32, 72],
       [29, 15, 99, 92, 47],
       [ 4, 93,  8, 76, 89]])

In [254]:
arr>55  

array([[ True,  True,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [False, False,  True,  True, False],
       [False,  True, False,  True,  True]])

In [256]:
arr[arr>55]  # Filter Condition

array([76, 59, 64, 69, 61, 56, 74, 81, 98, 72, 99, 92, 93, 76, 89])

In [259]:
arr[arr>80]

array([81, 98, 99, 92, 93, 89])

In [268]:
arr1 = np.random.randint(2,4,(3,3)) 
arr2 = np.random.randint(6,9,(3,3)) 

In [269]:
arr1

array([[3, 2, 2],
       [3, 3, 2],
       [3, 3, 3]])

In [270]:
arr2

array([[8, 6, 8],
       [8, 8, 8],
       [7, 7, 7]])

In [271]:
arr1*arr2

array([[24, 12, 16],
       [24, 24, 16],
       [21, 21, 21]])

In [272]:
arr1@arr2

array([[54, 48, 54],
       [62, 56, 62],
       [69, 63, 69]])

In [274]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [278]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [280]:
arr + a   # boardcasting 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [281]:
arr + np.array(([1,2,3]))

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [291]:
arr = np.random.rand(5,4)

In [292]:
arr

array([[0.03725437, 0.08320636, 0.2414828 , 0.91830538],
       [0.98583953, 0.18340059, 0.73076709, 0.98361388],
       [0.92240057, 0.02325512, 0.88856795, 0.35125226],
       [0.88268481, 0.71442215, 0.3141206 , 0.4584303 ],
       [0.38486622, 0.42984584, 0.02869595, 0.86923092]])

In [293]:
np.sqrt(arr)

array([[0.19301391, 0.28845512, 0.49140899, 0.95828251],
       [0.99289452, 0.42825295, 0.85484916, 0.9917731 ],
       [0.96041687, 0.1524963 , 0.94263882, 0.59266539],
       [0.93951307, 0.84523497, 0.56046463, 0.67707481],
       [0.62037587, 0.65562629, 0.16939878, 0.93232554]])

In [294]:
np.log(arr)

array([[-3.28998606, -2.48643154, -1.42095704, -0.08522529],
       [-0.01426168, -1.69608252, -0.31366048, -0.01652186],
       [-0.08077569, -3.76122984, -0.11814416, -1.04625062],
       [-0.12478709, -0.33628124, -1.15797829, -0.77994702],
       [-0.95485948, -0.84432866, -3.55099939, -0.14014646]])

In [295]:
arr1 = np.random.randint(2,5, (5,5))

In [296]:
arr1

array([[4, 3, 3, 3, 2],
       [4, 4, 4, 3, 3],
       [2, 4, 2, 2, 4],
       [3, 4, 4, 3, 2],
       [3, 4, 4, 2, 2]])

In [298]:
np.log(arr1)

array([[1.38629436, 1.09861229, 1.09861229, 1.09861229, 0.69314718],
       [1.38629436, 1.38629436, 1.38629436, 1.09861229, 1.09861229],
       [0.69314718, 1.38629436, 0.69314718, 0.69314718, 1.38629436],
       [1.09861229, 1.38629436, 1.38629436, 1.09861229, 0.69314718],
       [1.09861229, 1.38629436, 1.38629436, 0.69314718, 0.69314718]])

In [304]:
np.random.seed(13)  # Help in get same random data for a particular argument here its 13

In [300]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [301]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [303]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [305]:
np.random.seed(4)
np.random.rand(2, 4)

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026]])

In [306]:
np.random.seed(4)
np.random.rand(2, 4)

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026]])