In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'col1': [1,2,3,4,5],
    'col2': [12,23,43,45,65],
    'col3': "Chandan Kumar the Data Scientist"
})

In [3]:
df

col1  col2                              col3
0     1    12  Chandan Kumar the Data Scientist
1     2    23  Chandan Kumar the Data Scientist
2     3    43  Chandan Kumar the Data Scientist
3     4    45  Chandan Kumar the Data Scientist
4     5    65  Chandan Kumar the Data Scientist

In [4]:
df1 = pd.DataFrame({
    'col1': [1,2,3,4,5],
    'col2': [12,23,43,45,65],
    'col3': "Chandan Kumar the Data Scientist".split(' ')
})

In [5]:
df1

col1  col2       col3
0     1    12    Chandan
1     2    23      Kumar
2     3    43        the
3     4    45       Data
4     5    65  Scientist

In [7]:
df1['col4'] = df1['col1']**2

In [8]:
df1

col1  col2       col3  col4
0     1    12    Chandan     1
1     2    23      Kumar     4
2     3    43        the     9
3     4    45       Data    16
4     5    65  Scientist    25

In [14]:
df1['col5'] = df1['col3'][0]

In [15]:
df1

col1  col2       col3  col4     col5
0     1    12    Chandan     1  Chandan
1     2    23      Kumar     4  Chandan
2     3    43        the     9  Chandan
3     4    45       Data    16  Chandan
4     5    65  Scientist    25  Chandan

In [18]:
df1['col5'] = df1['col3'].str[0]

In [19]:
df1

col1  col2       col3  col4 col5
0     1    12    Chandan     1    C
1     2    23      Kumar     4    K
2     3    43        the     9    t
3     4    45       Data    16    D
4     5    65  Scientist    25    S

In [25]:
def test1(a):
    return  a**2

In [26]:
df1['col4_4'] = df1['col1'].apply(test1)

In [27]:
df1

col1  col2       col3  col4 col5  col4_4
0     1    12    Chandan     1    C       1
1     2    23      Kumar     4    K       4
2     3    43        the     9    t       9
3     4    45       Data    16    D      16
4     5    65  Scientist    25    S      25

In [33]:
def task2(s):
    if s == 'S':
        return 'S'
    else:
        return 'Z'

In [34]:
df1['col6'] = df1['col5'].apply(task2)

In [35]:
df1

col1  col2       col3  col4 col5  col4_4 col6
0     1    12    Chandan     1    C       1    Z
1     2    23      Kumar     4    K       4    Z
2     3    43        the     9    t       9    Z
3     4    45       Data    16    D      16    Z
4     5    65  Scientist    25    S      25    S

In [36]:
df1['col6_6'] = df1['col5'].apply(lambda a: 's' if a == 's' else 'z')

In [37]:
df1

col1  col2       col3  col4 col5  col4_4 col6 col6_6
0     1    12    Chandan     1    C       1    Z      z
1     2    23      Kumar     4    K       4    Z      z
2     3    43        the     9    t       9    Z      z
3     4    45       Data    16    D      16    Z      z
4     5    65  Scientist    25    S      25    S      z

In [40]:
lst1 = [1,2,3,4]
list(map(lambda x: x**2, lst1))

[1, 4, 9, 16]

In [41]:
df1['col7'] = df1['col3'].apply(lambda x: len(x))

In [42]:
df1

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7
0     1    12    Chandan     1    C       1    Z      z     7
1     2    23      Kumar     4    K       4    Z      z     5
2     3    43        the     9    t       9    Z      z     3
3     4    45       Data    16    D      16    Z      z     4
4     5    65  Scientist    25    S      25    S      z     9

In [43]:
df1['col7_7'] = df1['col3'].apply(len)

In [44]:
df1

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7  col7_7
0     1    12    Chandan     1    C       1    Z      z     7       7
1     2    23      Kumar     4    K       4    Z      z     5       5
2     3    43        the     9    t       9    Z      z     3       3
3     4    45       Data    16    D      16    Z      z     4       4
4     5    65  Scientist    25    S      25    S      z     9       9

In [45]:
import math

In [50]:
df1['col8'] = df1['col2'].apply(math.log10)

In [51]:
df1

col1  col2       col3  col4 col5  col4_4 col6 col6_6  col7  col7_7  \
0     1    12    Chandan     1    C       1    Z      z     7       7   
1     2    23      Kumar     4    K       4    Z      z     5       5   
2     3    43        the     9    t       9    Z      z     3       3   
3     4    45       Data    16    D      16    Z      z     4       4   
4     5    65  Scientist    25    S      25    S      z     9       9   

       col8  
0  1.079181  
1  1.361728  
2  1.633468  
3  1.653213  
4  1.812913

## Numpy

In [52]:
import numpy as np

In [54]:
l = ['data', 1, 2, 3, 4]
type(l)

list

In [55]:
np.array(l)

array(['data', '1', '2', '3', '4'], dtype='<U11')

In [56]:
type(np.array(l))

numpy.ndarray

In [60]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [61]:
a[1][1]

4

In [62]:
a2 = np.array([1,2,3,4], ndmin = 4)
a2

array([[[[1, 2, 3, 4]]]])

In [68]:
print(a2)
print(a2[0])
print(a2[0][0])
print(a2[0][0][0])
print(a2[0][0][0][0])
print(a2[0][0][0][1])
print(a2[0][0][0][2])
print(a2[0][0][0][3])

[[[[1 2 3 4]]]]
[[[1 2 3 4]]]
[[1 2 3 4]]
[1 2 3 4]
1
2
3
4


In [70]:
matrix = np.fromfunction(lambda i,j,k: i*j*k, (3,3,2), dtype=int)
matrix

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [71]:
matrix[1][1][1]

1

In [72]:
matrix[2][2][1]

4

In [73]:
arr3d = np.fromfunction(lambda i,j,k: i+j+k, (4,3,2), dtype=int)

In [74]:
arr3d

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6]]])

In [75]:
arr3d.ndim

3

In [76]:
arr3d.size

24

In [77]:
arr3d.shape

(4, 3, 2)

In [82]:
np.random.rand(10)

array([0.27655513, 0.12024359, 0.82161168, 0.11275431, 0.20053058,
       0.39407485, 0.93709518, 0.43062611, 0.0248513 , 0.05960504])

In [84]:
np.random.rand(10,4)

array([[0.94179318, 0.16739117, 0.64493351, 0.75293032],
       [0.92790184, 0.78122405, 0.18636348, 0.32694443],
       [0.65624787, 0.30652367, 0.9662393 , 0.75197119],
       [0.45998735, 0.76928709, 0.75590447, 0.95521313],
       [0.04657151, 0.30943501, 0.16272609, 0.84476424],
       [0.80342737, 0.42791628, 0.17765877, 0.38471819],
       [0.79940436, 0.91358639, 0.38166301, 0.67330682],
       [0.04121744, 0.23394001, 0.48517721, 0.35667244],
       [0.47620573, 0.23186895, 0.71031198, 0.63155841],
       [0.33164131, 0.88660248, 0.49177117, 0.80010164]])

In [83]:
np.random.randn(10)

array([-1.1082883 ,  1.09966616,  0.88748977,  0.07812233,  3.23451622,
       -0.86290937,  0.38863059,  0.18350829, -0.56130219,  1.36410709])

In [85]:
np.random.randn(10,4)

array([[-0.96256189, -0.55183844, -1.34566762,  0.23998828],
       [-0.07531506, -1.4797375 , -1.3922984 , -0.53481306],
       [ 0.96078   , -0.51797514, -0.30277754,  0.04304906],
       [-0.62595505,  0.86139013, -1.14275258, -0.23534405],
       [ 0.89215743, -0.20714805,  0.91659515,  0.10963361],
       [ 0.17390535, -0.31768317,  0.89310016,  0.10367621],
       [-0.06115563,  0.53457882, -1.67500043,  1.50028382],
       [ 0.02664154,  0.91255731, -0.67332452,  0.91913638],
       [-0.13978806, -1.27149602,  0.38512783,  1.88537348],
       [-0.30881363, -0.65078619, -1.43766229, -1.34934389]])

In [87]:
np.random.randint(0, 10)

6

In [88]:
arr3d.shape

(4, 3, 2)

In [89]:
arr3d.resize(4,2,1,3,1)

In [90]:
arr3d

array([[[[[0],
          [1],
          [1]]],


        [[[2],
          [2],
          [3]]]],



       [[[[1],
          [2],
          [2]]],


        [[[3],
          [3],
          [4]]]],



       [[[[2],
          [3],
          [3]]],


        [[[4],
          [4],
          [5]]]],



       [[[[3],
          [4],
          [4]]],


        [[[5],
          [5],
          [6]]]]])

In [91]:
arr3d.shape

(4, 2, 1, 3, 1)

In [92]:
arr3d.reshape(4, -1)

array([[0, 1, 1, 2, 2, 3],
       [1, 2, 2, 3, 3, 4],
       [2, 3, 3, 4, 4, 5],
       [3, 4, 4, 5, 5, 6]])

In [93]:
arr3d.reshape(5, -1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [97]:
arr3d.reshape(2, -12314123)

array([[0, 1, 1, 2, 2, 3, 1, 2, 2, 3, 3, 4],
       [2, 3, 3, 4, 4, 5, 3, 4, 4, 5, 5, 6]])

In [98]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
list(range(1, 10, .2))

TypeError: 'float' object cannot be interpreted as an integer

In [101]:
np.arange(1, 10, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [105]:
arr = np.random.rand(4,5)
arr

array([[0.37581583, 0.40283319, 0.96849053, 0.9600331 , 0.21358459],
       [0.29748666, 0.69057589, 0.09973164, 0.75469804, 0.412984  ],
       [0.97944203, 0.56207882, 0.218639  , 0.56357553, 0.30821493],
       [0.2884001 , 0.7866344 , 0.52664401, 0.84937775, 0.39442362]])

In [106]:
arr > .5

array([[False, False,  True,  True, False],
       [False,  True, False,  True, False],
       [ True,  True, False,  True, False],
       [False,  True,  True,  True, False]])

In [107]:
arr[arr > .5]

array([0.96849053, 0.9600331 , 0.69057589, 0.75469804, 0.97944203,
       0.56207882, 0.56357553, 0.7866344 , 0.52664401, 0.84937775])

In [108]:
arr

array([[0.37581583, 0.40283319, 0.96849053, 0.9600331 , 0.21358459],
       [0.29748666, 0.69057589, 0.09973164, 0.75469804, 0.412984  ],
       [0.97944203, 0.56207882, 0.218639  , 0.56357553, 0.30821493],
       [0.2884001 , 0.7866344 , 0.52664401, 0.84937775, 0.39442362]])

In [119]:
arr[[0,2], [2]]

array([0.96849053, 0.218639  ])

In [120]:
arr = np.random.rand(8, 5)
arr

array([[0.75093813, 0.94924499, 0.8706784 , 0.50755384, 0.15111439],
       [0.39587754, 0.92229491, 0.03181728, 0.55976596, 0.60017426],
       [0.31497117, 0.98905626, 0.47918682, 0.82311282, 0.2584359 ],
       [0.0493047 , 0.62076516, 0.02956145, 0.78519765, 0.28076388],
       [0.36395398, 0.21429987, 0.71854782, 0.7652033 , 0.83097545],
       [0.37402879, 0.14320256, 0.18503592, 0.79814999, 0.95520997],
       [0.27748632, 0.70237594, 0.19280217, 0.73699606, 0.97278393],
       [0.70687149, 0.38942329, 0.16965495, 0.27457695, 0.20610122]])

In [122]:
arr[1:8, 0:3]

array([[0.39587754, 0.92229491, 0.03181728],
       [0.31497117, 0.98905626, 0.47918682],
       [0.0493047 , 0.62076516, 0.02956145],
       [0.36395398, 0.21429987, 0.71854782],
       [0.37402879, 0.14320256, 0.18503592],
       [0.27748632, 0.70237594, 0.19280217],
       [0.70687149, 0.38942329, 0.16965495]])

In [124]:
arr[1:8, [1,3, 4,]]

array([[0.92229491, 0.55976596, 0.60017426],
       [0.98905626, 0.82311282, 0.2584359 ],
       [0.62076516, 0.78519765, 0.28076388],
       [0.21429987, 0.7652033 , 0.83097545],
       [0.14320256, 0.79814999, 0.95520997],
       [0.70237594, 0.73699606, 0.97278393],
       [0.38942329, 0.27457695, 0.20610122]])

In [126]:
a = np.array([[1,2], [3,4]])
b = np.array([[4,5], [6,7]])

In [127]:
a

array([[1, 2],
       [3, 4]])

In [128]:
b

array([[4, 5],
       [6, 7]])

In [129]:
a*b

array([[ 4, 10],
       [18, 28]])

In [131]:
m = a@b
m

array([[16, 19],
       [36, 43]])

In [132]:
m/0

C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_2540/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])