In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.zeros(5)+9.5

array([9.5, 9.5, 9.5, 9.5, 9.5])

In [9]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 1.33511018e-306],
       [1.29062229e-306, 7.56587585e-307, 1.37961302e-306,
        1.05699242e-307, 8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306],
       [8.01097889e-307, 1.37962660e-306, 6.89809904e-307,
        9.34609111e-307, 2.56765117e-312]])

In [15]:
np.linspace(2, 10, 10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [17]:
np.linspace(2, 10, 10).reshape(5,2)

array([[ 2.        ,  2.88888889],
       [ 3.77777778,  4.66666667],
       [ 5.55555556,  6.44444444],
       [ 7.33333333,  8.22222222],
       [ 9.11111111, 10.        ]])

In [18]:
np.linspace(2, 10, 10, endpoint=False).reshape(5,2)

array([[2. , 2.8],
       [3.6, 4.4],
       [5.2, 6. ],
       [6.8, 7.6],
       [8.4, 9.2]])

In [20]:
np.linspace(2, 10, 10, endpoint=False, retstep=True)

(array([2. , 2.8, 3.6, 4.4, 5.2, 6. , 6.8, 7.6, 8.4, 9.2]), 0.8)

In [22]:
np.logspace(2,4,10, base = 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [23]:
np.logspace(2,4,10, base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [28]:
a = np.arange(16).reshape(4, 4)

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a.max()

15

In [32]:
a.max(axis = 1)

array([ 3,  7, 11, 15])

In [33]:
a.max(axis = 0)

array([12, 13, 14, 15])

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [37]:
a/0

C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_3228/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0
C:\Users\CHANDA~1\AppData\Local\Temp/ipykernel_3228/4102073204.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/0


array([[nan, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
b = np.array([5,6,7,8])

In [40]:
a+b

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23]])

In [44]:
b.shape

(4,)

In [47]:
b.T

array([5, 6, 7, 8])

In [48]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [52]:
b

array([5, 6, 7, 8])

In [53]:
b.shape

(4,)

In [54]:
b = b.reshape(1,-1)

In [55]:
b

array([[5, 6, 7, 8]])

In [56]:
b.shape

(1, 4)

In [57]:
b.T

array([[5],
       [6],
       [7],
       [8]])

In [58]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
a + b.T

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [62]:
x = np.array([1,2,3])

In [63]:
x

array([1, 2, 3])

In [64]:
y = x

In [65]:
y

array([1, 2, 3])

In [66]:
z = np.copy(x)

In [67]:
z

array([1, 2, 3])

In [68]:
x[0] = 100

In [69]:
x

array([100,   2,   3])

In [70]:
y

array([100,   2,   3])

In [71]:
z

array([1, 2, 3])

In [72]:
id(x)

1988576856656

In [73]:
id(y)

1988576856656

In [74]:
id(z)

1988576855696

In [75]:
id(x[0])

1988588811728

In [76]:
id(y[0])

1988588811824

In [77]:
id(x[0]) == id(y[0])

True