In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport

In [3]:
df = pd.read_csv('Advertising.csv')

In [4]:
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [5]:
df.head(10)

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9
5           6    8.7   48.9       75.0    7.2
6           7   57.5   32.8       23.5   11.8
7           8  120.2   19.6       11.6   13.2
8           9    8.6    2.1        1.0    4.8
9          10  199.8    2.6       21.2   10.6

In [6]:
df.tail(10)

Unnamed: 0     TV  radio  newspaper  sales
190         191   39.5   41.1        5.8   10.8
191         192   75.5   10.8        6.0    9.9
192         193   17.2    4.1       31.6    5.9
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [7]:
df.describe()

Unnamed: 0          TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  200 non-null    int64  
 1   TV          200 non-null    float64
 2   radio       200 non-null    float64
 3   newspaper   200 non-null    float64
 4   sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB


In [15]:
pf = ProfileReport(df)
pf

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
pf.to_widgets()

In [20]:
## Multi collinearity - x1,x2,x3,x4 feature columnes, y Label column
# If there is a releationship between feature columns then its called multi collinearity
# Our data must be non multi collinear
# Because at time of learning there the model will start learning the feature datasets iteself
# If dataset is multicollinear then at time of adjustment learning parameter
# there is high chance that it will produce baises and end up learning relationship between features

In [21]:
# This data is not a multi collinear dataset

In [22]:
pf.to_file('DataProfileReport-1.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
## First model between Sales vs TV

In [24]:
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [42]:
x = df[["TV"]]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [43]:
y = df['sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [29]:
# our eq:
# sales = m*TV + c

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
linear = LinearRegression()

In [46]:
linear.fit(x, y)   # Calling the training find out best m and c

LinearRegression()

In [47]:
linear.intercept_  # Value of C 

7.032593549127693

In [48]:
linear.coef_      # slope m

array([0.04753664])

In [50]:
# Equation becomes:
# sales = 0.04753664*TV + 7.032593549127693   # This is our model

In [51]:
file = "linear_reg.sav"   # sav bytecode format

In [52]:
pickle.dump(linear, open(file, 'wb'))

In [53]:
linear.predict([[45]])

array([9.17174237])

In [55]:
sales = 0.04753664*45 + 7.032593549127693
sales

9.171742349127694

In [58]:
l = [5,3,6,45,31,676, 1001, 1111]

for i in l:
    print(linear.predict([[i]]))

[7.27027675]
[7.17520347]
[7.31781339]
[9.17174237]
[8.5062294]
[39.16736248]
[54.61677062]
[59.84580107]


In [59]:
[linear.predict([[i]]) for i in l]

[array([7.27027675]),
 array([7.17520347]),
 array([7.31781339]),
 array([9.17174237]),
 array([8.5062294]),
 array([39.16736248]),
 array([54.61677062]),
 array([59.84580107])]

In [60]:
saved_model = pickle.load(open(file, 'rb'))

In [61]:
saved_model.predict([[45]])

array([9.17174237])

In [62]:
[saved_model.predict([[i]]) for i in l]

[array([7.27027675]),
 array([7.17520347]),
 array([7.31781339]),
 array([9.17174237]),
 array([8.5062294]),
 array([39.16736248]),
 array([54.61677062]),
 array([59.84580107])]

In [65]:
linear.score(x,y)   ## Score return coeff of R^2 (1-RSS/TSS)

0.611875050850071

In [66]:
saved_model.score(x,y)

0.611875050850071